#!/usr/bin/env bash
# Install nginx web server

# Install nginx
apt-get update -y
apt-get install -y nginx

# Make sure nginx is enabled and started using init script (not systemctl)
service nginx start

# Create a simple HTML page with required content
echo "Holberton School" > /var/www/html/index.html

# Restart nginx using init script
service nginx restart